"""Generate a C++ source file that exercises every Signal declared by every
known part descriptor. The compile result is the sync test: if a part's
Python signal table claims `imu.last_accel()` exists but the C++ class
renames or deletes that method, the build breaks loudly.

Output file: tests/test_codegen_signals.gen.cpp (regenerated by CMake on
every configure; see tests/CMakeLists.txt). This script intentionally
imports the descriptor classes and walks their `signals` ClassVar — there's
no separate registry, so adding a new part with a `signals` table picks it
up automatically as long as the import below covers it.

Run standalone:
    PYTHONPATH=python/manta_codegen/src python3 \\
        python/manta_codegen/scripts/emit_signal_sync_test.py \\
        tests/test_codegen_signals.gen.cpp
"""

from __future__ import annotations

import sys
from pathlib import Path

_SRC = Path(__file__).resolve().parents[1] / "src"
if str(_SRC) not in sys.path:
    sys.path.insert(0, str(_SRC))

from manta_codegen.core import PartDescriptor
from manta_codegen.parts.sensor.imu import IMU
from manta_codegen.parts.sensor.dvl import DVL
from manta_codegen.parts.sensor.magnetometer import Magnetometer
from manta_codegen.parts.actuator.thruster import Thruster
from manta_codegen.parts.articulation.motor import Motor


# Default fixtures: one Python instance per part class with `signals`. The
# script walks `descriptor.emit_constructor_args()` so the C++ constructor
# matches whatever the descriptor would have emitted for codegen anyway —
# the constructor expression is itself part of the surface we want to keep
# in sync.
FIXTURES: list[PartDescriptor] = [
    IMU("imu"),
    DVL("dvl"),
    Magnetometer("mag"),
    Thruster("thr", max_thrust=2.0),
    Motor("motor"),
]


HEADER = """\
// AUTO-GENERATED by python/manta_codegen/scripts/emit_signal_sync_test.py.
// Do not edit by hand. Regenerated by CMake at configure time.
//
// One TEST_CASE per part fixture exercises every Signal declared in the
// descriptor's `signals` table — proving the Python expressions
// (cpp_read_exprs / cpp_write_stmt) compile against the actual C++ part
// API. If a part's class renames an accessor without updating the Python
// signal, the build breaks here.

#include <doctest/doctest.h>

#include "manta/core/craft.hpp"
"""

PER_PART_TEMPLATE = """\
TEST_CASE("Signals stay in sync: {test_name}") {{
    manta::Craft craft("sync");
    auto& {var} = craft.root().add<{cpp_class}>({ctor_args});
    craft.root().compute_params();
    (void){var};   // suppress unused-variable warnings if part has no signals
{body}
}}
"""


def _read_to_local(read_expr: str, accessor: str, local_name: str) -> str:
    """Emit a `(void)(...);` line that evaluates the read expression.
    The substitution doubles literal { and } in the C++ expression, then
    str.format substitutes {accessor}."""
    return f"    (void)({read_expr.format(accessor=accessor)});"


def _write_to_local(write_stmt: str, accessor: str, n_floats: int) -> str:
    """Emit the cpp_write_stmt with v0..v_{n-1} = float(0). The .format call
    substitutes {accessor} and {v0}..{v_{n-1}}."""
    fmt_args = {"accessor": accessor}
    for i in range(n_floats):
        fmt_args[f"v{i}"] = "static_cast<float>(0)"
    return "    " + write_stmt.format(**fmt_args)


def emit_for_part(part: PartDescriptor) -> str:
    headers = [part.cpp_header]
    cpp_class = part.cpp_class
    if not cpp_class:
        raise RuntimeError(
            f"Part {type(part).__name__}: cpp_class must be set for sync test")

    var = part.name + "_part"
    accessor = var
    body_lines: list[str] = []
    for sig in part.signals:
        body_lines.append(f"    // signal: {sig.name} ({sig.direction}, {sig.n_floats} float{'s' if sig.n_floats != 1 else ''})")
        if sig.direction == "out":
            for expr in sig.cpp_read_exprs:
                body_lines.append(_read_to_local(expr, accessor, var))
        else:
            body_lines.append(_write_to_local(sig.cpp_write_stmt, accessor, sig.n_floats))

    return PER_PART_TEMPLATE.format(
        test_name=type(part).__name__,
        var=var,
        cpp_class=cpp_class,
        ctor_args=part.emit_constructor_args(),
        body="\n".join(body_lines) if body_lines else "",
    ), headers


def main(out_path: str) -> None:
    parts_emit = [emit_for_part(p) for p in FIXTURES]
    seen_headers: set[str] = set()
    extra_headers: list[str] = []
    for _, headers in parts_emit:
        for h in headers:
            if h and h not in seen_headers:
                seen_headers.add(h)
                extra_headers.append(h)

    out = [HEADER]
    out.extend(f'#include "{h}"' for h in extra_headers)
    out.append("")
    out.extend(body for body, _ in parts_emit)

    Path(out_path).write_text("\n".join(out))


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(f"usage: {sys.argv[0]} <out_path>", file=sys.stderr)
        sys.exit(2)
    main(sys.argv[1])
