#!/bin/sh
# Generated by manta.codegen.wasm. Build the WASM module with Emscripten.
#   ./build.sh            # release (-O3)
#   ./build.sh -O0 -g     # pass extra emcc flags through
set -e
cd "$(dirname "$0")"

emcc -O3 "$@" \
  quad_kernels.c \
  quad_abi.c \
  -o quad.mjs \
  -s MODULARIZE=1 \
  -s EXPORT_ES6=1 \
  -s ENVIRONMENT=web,worker,node \
  -s ALLOW_MEMORY_GROWTH=1 \
  -s EXPORTED_FUNCTIONS=_malloc,_free \
  -s EXPORTED_RUNTIME_METHODS=ccall,cwrap,HEAPF64 \
  -Wno-unused-parameter -Wno-unused-variable

echo "built quad.mjs + quad.wasm"
