#include <cmath>
#include <doctest/doctest.h>

#include "../include/manta/core/craft.hpp"
#include "../include/manta/core/noise.hpp"
#include "../include/manta/fields/gravity_field.hpp"
#include "../include/manta/parts/sensor/imu.hpp"
#include "../include/manta/parts/structure/point_mass.hpp"
#include "../include/manta/parts/actuator/gimbaled_thruster.hpp"
#include "../include/manta/parts/actuator/prop_thruster.hpp"
#include "../include/manta/parts/actuator/thruster.hpp"
#include "test_helpers.hpp"

using namespace manta;
using namespace manta::geom;
using namespace manta::parts;
using namespace manta::fields;

// ---- PointMass tests ----

TEST_CASE("PointMass: contributes mass to root compute_params") {
    Craft c("test");
    auto& pm = c.root().add<PointMass>("body", 2.5f);
    c.root().compute_params();
    CHECK(c.root().get_mass() == doctest::Approx(2.5f));
}

TEST_CASE("PointMass: no wrench generated by update") {
    Craft c("test");
    c.root().add<PointMass>("body", 1.0f);
    c.update();
    auto w = c.root().net_wrench();
    CHECK(test::approx_equal(w.force(),  Vec3<PartFrame>::zero()));
    CHECK(test::approx_equal(w.torque(), Vec3<PartFrame>::zero()));
}

// ---- Thruster tests ----

TEST_CASE("Thruster: zero throttle → no wrench") {
    Craft c("test");
    auto& t = c.root().add<Thruster>("t", 100.0f);
    t.set_throttle(0.0f);
    c.update();
    CHECK(test::approx_equal(c.root().net_wrench().force(), Vec3<PartFrame>::zero()));
}

TEST_CASE("Thruster: full throttle → max thrust along +z") {
    Craft c("test");
    auto& t = c.root().add<Thruster>("t", 10.0f);
    t.set_throttle(1.0f);
    c.update();
    CHECK(test::approx_equal(c.root().net_wrench().force(), Vec3<PartFrame>{0, 0, 10}));
}

TEST_CASE("Thruster: half throttle → half force") {
    Craft c("test");
    auto& t = c.root().add<Thruster>("t", 8.0f);
    t.set_throttle(0.5f);
    c.update();
    CHECK(test::approx_equal(c.root().net_wrench().force(), Vec3<PartFrame>{0, 0, 4}));
}

TEST_CASE("Thruster: throttle clamped to [0,1]") {
    Craft c("test");
    auto& t = c.root().add<Thruster>("t", 10.0f);
    t.set_throttle(2.0f);
    CHECK(t.throttle() == doctest::Approx(1.0f));
    t.set_throttle(-0.5f);
    CHECK(t.throttle() == doctest::Approx(0.0f));
}

TEST_CASE("Thruster: custom direction") {
    Craft c("test");
    auto& t = c.root().add<Thruster>("t", 5.0f, Vec3<PartFrame>{1, 0, 0});
    t.set_throttle(1.0f);
    c.update();
    CHECK(test::approx_equal(c.root().net_wrench().force(), Vec3<PartFrame>{5, 0, 0}));
}

TEST_CASE("Thruster: thrust drives craft dynamics") {
    // 1 kg craft, 1 N thrust in +z PartFrame (= +z SceneFrame when identity orient).
    // After 1 s: v_z = 1 m/s.
    Craft c("test");
    auto& t = c.root().add<Thruster>("t", 1.0f);
    t.set_throttle(1.0f);
    t.set_mass(1.0f);
    c.root().compute_params();

    c.update(1.0f);

    auto vel = c.scene_to_craft().vel_linear();
    CHECK(test::approx_equal(vel, Vec3<SceneFrame>{0, 0, 1}));
}

// ---- PropThruster tests ----

TEST_CASE("PropThruster: zero throttle → no force, no torque") {
    Craft c("test");
    auto& pt = c.root().add<PropThruster>("pt", 10.0f, 0.02f, false);
    pt.set_throttle(0.0f);
    c.update();
    CHECK(test::approx_equal(c.root().net_wrench().force(),  Vec3<PartFrame>::zero()));
    CHECK(test::approx_equal(c.root().net_wrench().torque(), Vec3<PartFrame>::zero()));
}

TEST_CASE("PropThruster: full throttle → thrust + counter-torque") {
    // max_thrust=10 N, kt=0.02, CCW (sign=-1)
    // Expected force: (0, 0, 10)
    // Expected torque: direction * (10 * 0.02 * -1) = (0, 0, -0.2)
    Craft c("test");
    auto& pt = c.root().add<PropThruster>("pt", 10.0f, 0.02f, /*cw=*/false);
    pt.set_throttle(1.0f);
    c.update();
    auto w = c.root().net_wrench();
    CHECK(test::approx_equal(w.force(),  Vec3<PartFrame>{0, 0, 10}));
    CHECK(test::approx_equal(w.torque(), Vec3<PartFrame>{0, 0, -0.2f}));
}

TEST_CASE("PropThruster: CW prop → positive torque sign") {
    Craft c("test");
    auto& pt = c.root().add<PropThruster>("pt", 10.0f, 0.02f, /*cw=*/true);
    pt.set_throttle(1.0f);
    c.update();
    auto w = c.root().net_wrench();
    CHECK(test::approx_equal(w.force(),  Vec3<PartFrame>{0, 0, 10}));
    CHECK(test::approx_equal(w.torque(), Vec3<PartFrame>{0, 0, 0.2f}));
}

TEST_CASE("PropThruster: half throttle → half torque") {
    // thrust = 10 * 0.5 = 5; torque_z = 5 * 0.02 * -1 = -0.1
    Craft c("test");
    auto& pt = c.root().add<PropThruster>("pt", 10.0f, 0.02f, false);
    pt.set_throttle(0.5f);
    c.update();
    auto w = c.root().net_wrench();
    CHECK(w.force().z()  == doctest::Approx(5.0f));
    CHECK(w.torque().z() == doctest::Approx(-0.1f));
}

// ---- GimbaledThruster tests ----

TEST_CASE("GimbaledThruster: zero gimbal → thrust along base direction") {
    Craft c("test");
    auto& t = c.root().add<GimbaledThruster>("g", 10.0f);
    t.set_throttle(1.0f);
    t.set_gimbal(0.0f, 0.0f);
    c.update();
    auto f = c.root().net_wrench().force();
    CHECK(test::approx_equal(f, Vec3<PartFrame>{0, 0, 10}));
}

TEST_CASE("GimbaledThruster: gimbal angles clamped to max_angle") {
    Craft c("test");
    auto& t = c.root().add<GimbaledThruster>("g", 10.0f, 0.1f);
    t.set_gimbal(1.0f, -1.0f);
    CHECK(t.pitch() == doctest::Approx( 0.1f));
    CHECK(t.yaw()   == doctest::Approx(-0.1f));
}

TEST_CASE("GimbaledThruster: small pitch deflection tilts thrust toward +x") {
    // base = (0,0,1); pitch=+0.1 rad → thrust ≈ (sin(0.1), 0, cos(0.1)) for yaw=0
    Craft c("test");
    auto& t = c.root().add<GimbaledThruster>("g", 10.0f, 0.5f);
    t.set_throttle(1.0f);
    t.set_gimbal(0.1f, 0.0f);
    c.update();
    auto f = c.root().net_wrench().force();
    CHECK(f.x() == doctest::Approx(10.0f * std::sin(0.1f)).epsilon(1e-4f));
    CHECK(f.y() == doctest::Approx(0.0f).epsilon(1e-4f));
    CHECK(f.z() == doctest::Approx(10.0f * std::cos(0.1f)).epsilon(1e-4f));
}

TEST_CASE("GimbaledThruster: deflected thrust at offset point produces torque") {
    // Engine offset below CoM (-z by 1m), small pitch deflection produces
    // torque about y-axis → expected sign matches "engine bottom shoves +x".
    Craft c("test");
    auto& t = c.root().add<GimbaledThruster>("g", 10.0f, 0.5f);
    StaticLink<ParentFrame, PartFrame> tf{
        Vec3<ParentFrame>{0, 0, -1},
        Ori<ParentFrame>::identity()};
    t.set_transform(tf);
    t.set_throttle(1.0f);
    t.set_gimbal(0.1f, 0.0f);
    c.update();
    // Force in CraftFrame at point (0,0,-1): F = (10 sin0.1, 0, 10 cos0.1)
    // Torque about origin = r × F = (0,0,-1) × F = (0*Fz - (-1)*0, (-1)*Fx - 0*Fz, 0)
    //                     = (0, -Fx, 0). For Fx > 0, expect negative y-torque,
    // which would pitch the rocket nose-down... wait, that's the convention check.
    // Just verify torque magnitude and sign correctness here.
    auto tq = c.root().net_wrench().torque();
    CHECK(tq.y() == doctest::Approx(-10.0f * std::sin(0.1f)).epsilon(1e-4f));
}

// ---- GravityField tests ----

TEST_CASE("GravityField: default g is -9.81 in -z") {
    GravityField gf;
    CHECK(gf.g().z() == doctest::Approx(-9.81f));
    CHECK(gf.g().x() == doctest::Approx(0.0f));
}

TEST_CASE("GravityField: register_field and field access from part") {
    // A part that reads the gravity field and applies the force.
    struct GravPart : public Part {
        explicit GravPart(std::string n) : Part(std::move(n)) {}
        void update() override {
            auto& gf = field<GravityField>();
            // gravity is in SceneFrame; we apply it in PartFrame (identity craft orientation).
            // Simplified: just check we can access the field.
            auto g_scene = gf.g();
            // For identity craft orientation, scene frame == craft frame == part frame.
            apply_force_at(Vec3<PartFrame>::from_raw(g_scene.raw()) * get_mass());
        }
    };

    GravityField gf{Vec3<SceneFrame>{0, 0, -9.81f}};
    Craft c("test");
    c.register_field(gf);

    auto& gp = c.root().add<GravPart>("gp");
    gp.set_mass(2.0f);
    c.root().compute_params();

    c.update();

    // F_z = 2 * -9.81 = -19.62
    auto f = c.root().net_wrench().force();
    CHECK(f.z() == doctest::Approx(-19.62f).epsilon(1e-3f));
    CHECK(f.x() == doctest::Approx(0.0f).epsilon(1e-4f));
}

// ---- IMU tests ----

TEST_CASE("IMU: reports zero acceleration and angular velocity at rest") {
    // Craft at rest with no forces — acceleration should be zero, gyro zero.
    Craft c("test");
    auto& imu = c.root().add<IMU>("imu");
    imu.set_mass(0.1f);
    c.root().compute_params();

    // Two ticks: first tick sets scene_to_part (acc = 0 from previous state),
    // second tick reads it.
    c.update(0.01f);
    c.update(0.01f);

    // No forces → zero acceleration integrated over the tick.
    CHECK(test::approx_equal(imu.last_accel(), Vec3<PartFrame>::zero()));
    CHECK(test::approx_equal(imu.last_gyro(),  Vec3<PartFrame>::zero()));
}

TEST_CASE("IMU: reports non-zero acceleration under thrust (no noise)") {
    // 1 kg craft, 2 N in +z → a = 2 m/s^2.
    Craft c("test");
    auto& t   = c.root().add<Thruster>("t",   2.0f);
    auto& imu = c.root().add<IMU>("imu");
    t.set_throttle(1.0f);
    t.set_mass(1.0f);
    c.root().compute_params();

    // Tick 1: force → acceleration computed and stored in scene_to_craft.
    c.update(0.01f);
    // Tick 2: kinematic pass propagates the new acceleration to scene_to_part.
    c.update(0.01f);

    // IMU reads acceleration_body() which comes from scene_to_part.acc_linear
    // rotated to part frame. With identity orientation: a_part = (0,0,2).
    CHECK(imu.last_accel().z() == doctest::Approx(2.0f).epsilon(1e-3f));
}

TEST_CASE("IMU: noise zero-sigma leaves measurement unchanged") {
    noise_seed(0);
    Craft c("test");
    auto& imu = c.root().add<IMU>("imu", ImuNoiseParams{.accel_sigma=0.0f, .gyro_sigma=0.0f});
    c.root().compute_params();
    c.update(0.01f);
    c.update(0.01f);

    // Zero sigma → no perturbation.
    CHECK(test::approx_equal(imu.last_accel(), Vec3<PartFrame>::zero()));
    CHECK(test::approx_equal(imu.last_gyro(),  Vec3<PartFrame>::zero()));
}
