"""The C-ABI shim — the one thing the WASM backend adds over the kernels.

The CasADi-emitted kernels already are standalone flat-C (`int k(const
double** arg, double** res, …)`), so the only glue WASM needs is a thin
per-entry function on a layout the JS side can drive without knowing
CasADi's arg/res pointer-array convention:

    int <base>_<method>(const double* in, double* out);

`in` is the concatenation of every kernel input (in `ep.args` order); `out`
the concatenation of every kernel output (writes, then returns). The shim
slices both into the `arg[]`/`res[]` pointer arrays at the offsets computed
once in `layout.py` and calls the kernel — reusing the exact same flat-C
call boilerplate (`emit_kernel_call`) the C++ wrapper bodies use.

`EMSCRIPTEN_KEEPALIVE` auto-exports each shim from the `.wasm`; the guard
keeps the file compilable by a plain C compiler too (so the ABI can be
round-trip tested without an Emscripten toolchain on PATH)."""

from __future__ import annotations

from ..cpp._casadi import emit_kernel_call

_PREAMBLE = """\
/* Generated by manta.codegen.wasm. Do not edit by hand. */
/* Thin flat-double C ABI over the CasADi kernels, exported to WASM. */

#ifdef __EMSCRIPTEN__
#include <emscripten/emscripten.h>
#else
#define EMSCRIPTEN_KEEPALIVE
#endif
"""


def emit_abi_c(layouts, *, basename: str) -> str:
    """Render the C-ABI shim translation unit for a Module's entry layouts."""
    lines = [_PREAMBLE, f'#include "{basename}_kernels.h"', ""]
    for lay in layouts:
        args = [f"in + {s.off}" for s in lay.inputs]
        results = [(j, f"out + {s.off}") for j, s in enumerate(lay.outputs)]
        lines.append("EMSCRIPTEN_KEEPALIVE")
        lines.append(f"int {lay.shim}(const double* in, double* out) {{")
        if not lay.inputs:
            lines.append("    (void)in;")
        if not lay.outputs:
            lines.append("    (void)out;")
        lines += emit_kernel_call(lay.kernel, args, results)
        lines.append("    return 0;")
        lines.append("}")
        lines.append("")
    return "\n".join(lines) + "\n"
