"""The Emscripten build script.

Emits a `build.sh` that compiles the CasADi kernels + the C-ABI shim into a
`<basename>.mjs` + `<basename>.wasm` pair. The shims auto-export via
`EMSCRIPTEN_KEEPALIVE`; we additionally export `malloc`/`free` (the JS
runtime allocates the flat I/O buffers) and the heap + `ccall` runtime
helpers it marshals through. `MODULARIZE`+`EXPORT_ES6` give the clean
factory-function ES module `js.py` imports."""

from __future__ import annotations


def emit_build_sh(*, basename: str) -> str:
    return _TEMPLATE.replace("__BASENAME__", basename)


_TEMPLATE = r"""#!/bin/sh
# Generated by manta.codegen.wasm. Build the WASM module with Emscripten.
#   ./build.sh            # release (-O3)
#   ./build.sh -O0 -g     # pass extra emcc flags through
set -e
cd "$(dirname "$0")"

emcc -O3 "$@" \
  __BASENAME___kernels.c \
  __BASENAME___abi.c \
  -o __BASENAME__.mjs \
  -s MODULARIZE=1 \
  -s EXPORT_ES6=1 \
  -s ENVIRONMENT=web,worker,node \
  -s ALLOW_MEMORY_GROWTH=1 \
  -s EXPORTED_FUNCTIONS=_malloc,_free \
  -s EXPORTED_RUNTIME_METHODS=ccall,cwrap,HEAPF64 \
  -Wno-unused-parameter -Wno-unused-variable

echo "built __BASENAME__.mjs + __BASENAME__.wasm"
"""
