"""The emitted JavaScript runtime.

`<basename>.js` is a hand-free ES module: it imports the Emscripten factory
(`./<basename>.mjs`, produced by the build step) and embeds the descriptor,
and exposes two layers:

  * `Runtime.call(method, args)` — the generic flat-marshalling layer. Packs
    a `{slotName: Float64Array | number}` map into the WASM heap per the
    descriptor's per-entry layout, invokes the shim, and unpacks every output
    slot back into a `{slotName: Float64Array}` map. Works for any Module.
  * `runtime.sim()` → a `Sim` convenience mirroring the numpy view for a
    THREADED simulation Module: a held flat state, `step(dt, {u})`, and
    `reading(name)`.

The JS contains no manta-specific logic — only the descriptor drives it — so
this template is identical for every Module; only the embedded JSON differs.
"""

from __future__ import annotations

import json


def emit_js(descriptor: dict, *, basename: str) -> str:
    blob = json.dumps(descriptor, indent=2)
    return _TEMPLATE.replace("__BASENAME__", basename).replace(
        "__DESCRIPTOR__", blob)


_TEMPLATE = r"""// Generated by manta.codegen.wasm. Do not edit by hand.
import createModule from "./__BASENAME__.mjs";

export const descriptor = __DESCRIPTOR__;

const byMethod = Object.fromEntries(
  descriptor.entryPoints.map((e) => [e.method, e]));

/** Resolve a field name given as a full dotted name or a unique suffix. */
function resolveName(key, names, label) {
  if (names.includes(key)) return key;
  const hits = names.filter((n) => n === key || n.endsWith("." + key));
  if (hits.length === 1) return hits[0];
  throw new Error(
    `${label} ${JSON.stringify(key)} is not a unique name in [${names}]`);
}

/** The low-level flat-buffer runtime over the WASM module. */
export class Runtime {
  constructor(Module) {
    this.M = Module;
    this._bufs = {}; // method -> {inPtr, outPtr, inView, outView}
  }

  _buffers(entry) {
    let b = this._bufs[entry.method];
    if (!b) {
      const inPtr = this.M._malloc(Math.max(entry.inSize, 1) * 8);
      const outPtr = this.M._malloc(Math.max(entry.outSize, 1) * 8);
      b = { inPtr, outPtr };
      this._bufs[entry.method] = b;
    }
    return b;
  }

  /** Call entry `method` with `{slotName: Float64Array | number}`; returns
   *  `{slotName: Float64Array}` for every output slot. */
  call(method, args = {}) {
    const entry = byMethod[method];
    if (!entry) throw new Error(`no entry point ${JSON.stringify(method)}`);
    const { inPtr, outPtr } = this._buffers(entry);
    const inHeap = new Float64Array(this.M.HEAPF64.buffer, inPtr, entry.inSize);
    inHeap.fill(0);
    for (const s of entry.in) {
      const v = args[s.name];
      if (v === undefined) continue; // unset TIME/NOISE/PARAMETER -> zeros
      if (typeof v === "number") inHeap[s.off] = v;
      else inHeap.set(v.subarray(0, s.size), s.off);
    }
    this.M.ccall(entry.shim, "number", ["number", "number"], [inPtr, outPtr]);
    const outHeap = new Float64Array(
      this.M.HEAPF64.buffer, outPtr, entry.outSize);
    const out = {};
    for (const s of entry.out) {
      out[s.name] = outHeap.slice(s.off, s.off + s.size);
    }
    return out;
  }

  /** A THREADED simulation-oracle convenience view. */
  sim() {
    return new Sim(this);
  }
}

/** Mirrors the numpy `NumpySim`: held flat state, `step(dt, {u})`,
 *  `reading(name)`. */
export class Sim {
  constructor(runtime) {
    this.rt = runtime;
    this.t = 0;
    this.state = Float64Array.from(descriptor.initialState);
    this._inputNames = descriptor.inputs.map((f) => f.name);
    this._u = {}; // held commands, full field name -> value
    for (const f of descriptor.inputs) this._u[f.name] = f.default;
    this._outputs = {};
    this._step = byMethod["step"];
    if (!this._step) throw new Error("Module exposes no `step` entry point");
  }

  /** Pack the held inputs (overlaid with this step's `u`) into a flat
   *  control vector in descriptor field order. */
  _packControl(u) {
    const merged = { ...this._u };
    for (const [k, v] of Object.entries(u || {})) {
      merged[resolveName(k, this._inputNames, "input")] = v;
    }
    const vec = [];
    for (const f of descriptor.inputs) {
      const v = merged[f.name];
      if (f.dim === 1) vec.push(typeof v === "number" ? v : v[0]);
      else for (let i = 0; i < f.dim; i++) vec.push(v[i]);
    }
    return Float64Array.from(vec);
  }

  /** Advance the held state by `dt`, applying commands `u`. Returns `this`. */
  step(dt, u = {}) {
    const args = {};
    for (const s of this._step.in) {
      if (s.kind === "state") args[s.name] = this.state;
      else if (s.kind === "control") args[s.name] = this._packControl(u);
      else if (s.kind === "timestep") args[s.name] = dt;
      else if (s.kind === "time") args[s.name] = this.t;
      // noise / parameter left unset -> zeros (noiseless oracle / baked p)
    }
    const out = this.rt.call("step", args);
    this._outputs = {};
    for (const s of this._step.out) {
      if (s.writesState) this.state = out[s.name];
      else this._outputs[s.name] = out[s.name];
    }
    this.t += dt;
    return this;
  }

  /** The latest reading for a sensor (full or unique-suffix name). */
  reading(name) {
    const names = Object.keys(this._outputs);
    return this._outputs[resolveName(name, names, "output")];
  }

  /** The held state slot `name` (full or unique-suffix) as a Float64Array. */
  slot(name) {
    const names = descriptor.stateSlots.map((s) => s.name);
    const s = descriptor.stateSlots.find(
      (x) => x.name === resolveName(name, names, "state slot"));
    return this.state.slice(s.off, s.off + s.dim);
  }
}

/** Instantiate the WASM module and return a ready `Runtime`. */
export async function load(opts = {}) {
  const Module = await createModule(opts);
  return new Runtime(Module);
}
"""
