"""The emitted JavaScript runtime.

`<basename>.js` is a hand-free ES module: it imports the Emscripten factory
(`./<basename>.mjs`, produced by the build step) and embeds the descriptor,
and exposes two layers:

  * `Runtime.call(method, args)` — the generic flat-marshalling layer. Packs
    a `{slotName: Float64Array | number}` map into the WASM heap per the
    descriptor's per-entry layout, invokes the shim, and unpacks every output
    slot back into a `{slotName: Float64Array}` map. Works for any Module.
  * A typed convenience view per transform, each mirroring the matching numpy
    view over the same shims — `runtime.sim()` (`Sim`: held state, `step` /
    `reading`), `runtime.filter()` (`Filter`: held `x`/`P`, `predict` /
    `update`), `runtime.regulator()` (`Regulator`: held operating point,
    `control` / `retarget` / `reprogram`).

The JS contains no manta-specific logic — only the descriptor drives it — so
this template is identical for every Module; only the embedded JSON differs.
"""

from __future__ import annotations

import json


def emit_js(descriptor: dict, *, basename: str) -> str:
    blob = json.dumps(descriptor, indent=2)
    return _TEMPLATE.replace("__BASENAME__", basename).replace(
        "__DESCRIPTOR__", blob)


_TEMPLATE = r"""// Generated by manta.codegen.wasm. Do not edit by hand.
import createModule from "./__BASENAME__.mjs";

export const descriptor = __DESCRIPTOR__;

const byMethod = Object.fromEntries(
  descriptor.entryPoints.map((e) => [e.method, e]));

const INPUT_NAMES = descriptor.inputs.map((f) => f.name);
const DEFAULT_U = Object.fromEntries(
  descriptor.inputs.map((f) => [f.name, f.default]));

const PARAM_NAMES = descriptor.params.map((f) => f.name);
const DEFAULT_PARAMS = Object.fromEntries(
  descriptor.params.map((f) => [f.name, f.default]));

/** Measurement field name -> the update entry method that folds it. */
const MEAS_ENTRY = {};
for (const e of descriptor.entryPoints)
  for (const s of e.in)
    if (s.kind === "measurement") {
      if (MEAS_ENTRY[s.name] !== undefined)
        throw new Error(
          `descriptor: measurement ${JSON.stringify(s.name)} is consumed ` +
          `by both ${MEAS_ENTRY[s.name]} and ${e.method} — update() ` +
          `dispatch would be ambiguous`);
      MEAS_ENTRY[s.name] = e.method;
    }
const MEAS_NAMES = Object.keys(MEAS_ENTRY);

/** Resolve a field name given as a full dotted name or a unique suffix. */
function resolveName(key, names, label) {
  if (names.includes(key)) return key;
  const hits = names.filter((n) => n === key || n.endsWith("." + key));
  if (hits.length === 1) return hits[0];
  throw new Error(
    `${label} ${JSON.stringify(key)} is not a unique name in [${names}]`);
}

/** Pack `{name: value}` (full or unique-suffix names), overlaid on the
 *  `base` defaults, into a flat vector over `fields` in descriptor order. */
function packFields(overrides, base, fields, names, label) {
  const merged = { ...base };
  for (const [k, v] of Object.entries(overrides || {}))
    merged[resolveName(k, names, label)] = v;
  const vec = [];
  for (const f of fields) {
    const v = merged[f.name];
    if (f.dim === 1) vec.push(typeof v === "number" ? v : v[0]);
    else for (let i = 0; i < f.dim; i++) vec.push(v[i]);
  }
  return Float64Array.from(vec);
}

/** Pack `{input: value}` overlaid on the `base` command defaults. */
function packControl(u, base) {
  return packFields(u, base, descriptor.inputs, INPUT_NAMES, "input");
}

/** Pack `{parameter: value}` overlaid on the `base` promoted-parameter
 *  defaults. The declared defaults ARE the baked model values — leaving a
 *  parameter slot unset would run the physics with p = 0, not "baked p". */
function packParams(overrides, base) {
  return packFields(overrides, base, descriptor.params, PARAM_NAMES,
                    "parameter");
}

/** A seeded Gaussian noise source mirroring the numpy `NoiseDriver`: an
 *  independent N(0, sigma^2) draw per active (sigma > 0) noise channel per
 *  step. Attach with `sim.attachDriver(new NoiseDriver(seed))`; without one
 *  the sim is a noiseless oracle (the declared sigmas are inert). */
export class NoiseDriver {
  constructor(seed = 0) {
    this._s = seed >>> 0;
    this._spare = null;
  }
  _uniform() { // mulberry32
    this._s = (this._s + 0x6d2b79f5) >>> 0;
    let z = this._s;
    z = Math.imul(z ^ (z >>> 15), z | 1);
    z ^= z + Math.imul(z ^ (z >>> 7), z | 61);
    return (((z ^ (z >>> 14)) >>> 0) + 0.5) / 4294967296;
  }
  _normal() { // Box-Muller
    if (this._spare !== null) {
      const v = this._spare;
      this._spare = null;
      return v;
    }
    const r = Math.sqrt(-2 * Math.log(this._uniform()));
    const a = 2 * Math.PI * this._uniform();
    this._spare = r * Math.sin(a);
    return r * Math.cos(a);
  }
  /** Flat draw over the descriptor's noise fields (zeros where sigma = 0). */
  sample() {
    const vec = [];
    for (const f of descriptor.noise) {
      const sigma = f.sigma || 0;
      for (let i = 0; i < f.dim; i++)
        vec.push(sigma > 0 ? sigma * this._normal() : 0);
    }
    return Float64Array.from(vec);
  }
}

/** Build a flat ambient state: a `Float64Array` is taken verbatim, otherwise
 *  a `{slotName: value}` map (full or unique-suffix) is merged over `base`. */
function packState(state, base) {
  if (state instanceof Float64Array) return state;
  const vec = Float64Array.from(base);
  const names = descriptor.stateSlots.map((s) => s.name);
  for (const [k, v] of Object.entries(state || {})) {
    const s = descriptor.stateSlots.find(
      (x) => x.name === resolveName(k, names, "state slot"));
    if (s.dim === 1 && typeof v === "number") vec[s.off] = v;
    else for (let i = 0; i < s.dim; i++) vec[s.off + i] = v[i];
  }
  return vec;
}

/** Unpack a flat control vector into `{input: value}` by descriptor order. */
function unpackControl(u) {
  const out = {};
  let off = 0;
  for (const f of descriptor.inputs) {
    out[f.name] = f.dim === 1 ? u[off] : u.slice(off, off + f.dim);
    off += f.dim;
  }
  return out;
}

/** The low-level flat-buffer runtime over the WASM module. */
export class Runtime {
  constructor(Module) {
    this.M = Module;
    this._bufs = {}; // method -> {inPtr, outPtr, inView, outView}
  }

  _buffers(entry) {
    let b = this._bufs[entry.method];
    if (!b) {
      const inPtr = this.M._malloc(Math.max(entry.inSize, 1) * 8);
      const outPtr = this.M._malloc(Math.max(entry.outSize, 1) * 8);
      b = { inPtr, outPtr };
      this._bufs[entry.method] = b;
    }
    return b;
  }

  /** Call entry `method` with `{slotName: Float64Array | Array | number}`;
   *  returns `{slotName: Float64Array}` for every output slot. Strict: an
   *  unknown arg key throws (a typo'd slot name must not be a silent
   *  no-op), and a value whose length disagrees with the slot's size
   *  throws (silent truncation / zero-padding reads as a physics bug).
   *  A slot left unset stays zero-filled — the documented base. */
  call(method, args = {}) {
    const entry = byMethod[method];
    if (!entry) throw new Error(`no entry point ${JSON.stringify(method)}`);
    const slotNames = new Set(entry.in.map((s) => s.name));
    for (const k of Object.keys(args))
      if (!slotNames.has(k))
        throw new Error(
          `${method}: unknown arg ${JSON.stringify(k)}; slots: ` +
          `[${entry.in.map((s) => s.name)}]`);
    const { inPtr, outPtr } = this._buffers(entry);
    const inHeap = new Float64Array(this.M.HEAPF64.buffer, inPtr, entry.inSize);
    inHeap.fill(0);
    for (const s of entry.in) {
      const v = args[s.name];
      if (v === undefined || v === null) continue; // unset -> zeros
      if (typeof v === "number") {
        if (s.size !== 1)
          throw new Error(
            `${method}: ${s.name} expects ${s.size} values, got a scalar`);
        inHeap[s.off] = v;
      } else {
        const arr = v instanceof Float64Array ? v : Float64Array.from(v);
        if (arr.length !== s.size)
          throw new Error(
            `${method}: ${s.name} expects ${s.size} values, got ` +
            `${arr.length}`);
        inHeap.set(arr, s.off);
      }
    }
    this.M.ccall(entry.shim, "number", ["number", "number"], [inPtr, outPtr]);
    const outHeap = new Float64Array(
      this.M.HEAPF64.buffer, outPtr, entry.outSize);
    const out = {};
    for (const s of entry.out) {
      out[s.name] = outHeap.slice(s.off, s.off + s.size);
    }
    return out;
  }

  /** Free the per-entry WASM heap buffers. Call when done with a runtime a
   *  page churns through (each entry's buffers are malloc'd once and would
   *  otherwise live as long as the WASM instance). */
  dispose() {
    for (const b of Object.values(this._bufs)) {
      this.M._free(b.inPtr);
      this.M._free(b.outPtr);
    }
    this._bufs = {};
  }

  /** A THREADED simulation-oracle convenience view. */
  sim() {
    return new Sim(this);
  }

  /** A predict/update Kalman-filter convenience view. */
  filter() {
    return new Filter(this);
  }

  /** A stateless control-law convenience view. */
  regulator() {
    return new Regulator(this);
  }
}

/** Mirrors the numpy `NumpySim`: held flat state, `step(dt, {u})`,
 *  `reading(name)`. */
export class Sim {
  constructor(runtime) {
    this.rt = runtime;
    this.t = 0;
    this.state = Float64Array.from(descriptor.initialState);
    this._u = { ...DEFAULT_U }; // held commands, full field name -> value
    this._params = { ...DEFAULT_PARAMS }; // promoted-parameter overrides
    this._driver = null;
    this._outputs = {};
    this._step = byMethod["step"];
    if (!this._step) throw new Error("Module exposes no `step` entry point");
  }

  /** Override promoted-parameter values (full or unique-suffix names);
   *  every subsequent step uses them. Mirrors numpy `set_parameters`. */
  setParameters(values) {
    for (const [k, v] of Object.entries(values || {}))
      this._params[resolveName(k, PARAM_NAMES, "parameter")] = v;
  }

  /** Attach a `NoiseDriver` so every active (sigma > 0) noise channel is
   *  sampled each step — truth becomes noisy with the declared sigmas.
   *  Without one the sim is a noiseless oracle. Returns the driver. */
  attachDriver(driver) {
    this._driver = driver;
    return driver;
  }

  /** Advance the held state by `dt`, applying commands `u`. Returns `this`. */
  step(dt, u = {}) {
    const args = {};
    for (const s of this._step.in) {
      if (s.kind === "state") args[s.name] = this.state;
      else if (s.kind === "control") args[s.name] = packControl(u, this._u);
      else if (s.kind === "parameter")
        args[s.name] = packParams({}, this._params);
      else if (s.kind === "noise" && this._driver)
        args[s.name] = this._driver.sample();
      else if (s.kind === "timestep") args[s.name] = dt;
      else if (s.kind === "time") args[s.name] = this.t;
      // noise without a driver stays zero (noiseless oracle)
    }
    const out = this.rt.call("step", args);
    this._outputs = {};
    for (const s of this._step.out) {
      if (s.writesState) this.state = out[s.name];
      else this._outputs[s.name] = out[s.name];
    }
    this.t += dt;
    return this;
  }

  /** The latest reading for a sensor (full or unique-suffix name). */
  reading(name) {
    const names = Object.keys(this._outputs);
    return this._outputs[resolveName(name, names, "output")];
  }

  /** The held state slot `name` (full or unique-suffix) as a Float64Array. */
  slot(name) {
    const names = descriptor.stateSlots.map((s) => s.name);
    const s = descriptor.stateSlots.find(
      (x) => x.name === resolveName(name, names, "state slot"));
    return this.state.slice(s.off, s.off + s.dim);
  }
}

/** Mirrors the numpy `NumpyFilter`: a held `x`/`P` estimate with baked
 *  per-sensor Joseph updates. You own the loop — update-then-predict:
 *
 *      for (const nm of sensors) flt.update(nm, sim.reading(nm), { u });
 *      flt.predict(dt, { u });
 */
export class Filter {
  constructor(runtime) {
    this.rt = runtime;
    if (!byMethod["predict"])
      throw new Error("Module exposes no `predict` entry point");
    const field = (n) => descriptor.stateFields.find((f) => f.name === n);
    if (!field("x") || !field("P"))
      throw new Error("Module is not a filter (no `x`/`P` state)");
    this.x = Float64Array.from(field("x").init);
    this.P = Float64Array.from(field("P").init);
    this._x0 = this.x.slice();
    this._P0 = this.P.slice();
  }

  // `x`/`P`/`Q` are threaded by name (as in numpy); everything else by kind.
  _run(entry, { u = {}, dt = 0, t = 0, z = null, Q = null } = {}) {
    const args = {};
    for (const s of entry.in) {
      if (s.name === "x") args.x = this.x;
      else if (s.name === "P") args.P = this.P;
      else if (s.name === "Q") {
        if (Q === null)
          throw new Error(
            `${entry.method}: matrix port Q has no built default — ` +
            `supply it (a zero-filled Q is not "baked Q")`);
        args.Q = Q;
      }
      else if (s.kind === "control") args[s.name] = packControl(u, DEFAULT_U);
      else if (s.kind === "parameter")
        args[s.name] = packParams({}, DEFAULT_PARAMS);
      else if (s.kind === "timestep") args[s.name] = dt;
      else if (s.kind === "time") args[s.name] = t;
      else if (s.kind === "measurement") args[s.name] = z;
    }
    const out = this.rt.call(entry.method, args);
    for (const s of entry.out) {
      if (s.name === "x") this.x = out.x;
      else if (s.name === "P") this.P = out.P;
    }
  }

  /** Advance the estimate by `dt` under commands `u`. Pass a flat (column-
   *  major) `Q` Float64Array to override the model's baked `L Σ Lᵀ`. */
  predict(dt, { u = {}, t = 0, Q = null } = {}) {
    const method = Q ? "predict_with_Q" : "predict";
    if (!byMethod[method])
      throw new Error(`Module exposes no \`${method}\` entry point`);
    this._run(byMethod[method], { u, dt, t, Q });
  }

  /** Fold one measurement at the current state through its baked Joseph
   *  kernel. `name` is a sensor name (full or unique-suffix). */
  update(name, z, { u = {}, t = 0 } = {}) {
    const full = resolveName(name, MEAS_NAMES, "sensor");
    const za = z instanceof Float64Array
      ? z : Float64Array.from(typeof z === "number" ? [z] : z);
    this._run(byMethod[MEAS_ENTRY[full]], { u, t, z: za });
  }

  /** The held estimate slot `name` (full or unique-suffix) as a Float64Array. */
  slot(name) {
    const names = descriptor.stateSlots.map((s) => s.name);
    const s = descriptor.stateSlots.find(
      (x) => x.name === resolveName(name, names, "state slot"));
    return this.x.slice(s.off, s.off + s.dim);
  }

  /** Reset the held estimate. `x` is a flat/`{slot: value}` estimate merged
   *  over the model's init; `P` is a flat covariance. Resets both to the
   *  model's init when called with no arguments. */
  reset({ x = null, P = null } = {}) {
    if (x === null && P === null) {
      this.x = this._x0.slice();
      this.P = this._P0.slice();
      return;
    }
    if (x !== null) this.x = packState(x, this._x0);
    if (P !== null)
      this.P = P instanceof Float64Array ? P.slice() : Float64Array.from(P);
  }
}

/** Flatten a matrix given as an array of ROWS into the column-major order the
 *  kernel buffer uses; a flat array of the right length passes through (it is
 *  already column-major, as `descriptor.matrixPorts[].init` is). */
function packMatrix(v, shape, name) {
  const [rows, cols] = shape;
  if (Array.isArray(v) && Array.isArray(v[0])) {
    if (v.length !== rows || v[0].length !== cols)
      throw new Error(
        `${name}: expected ${rows}x${cols}, got ${v.length}x${v[0].length}`);
    const out = new Float64Array(rows * cols);
    for (let c = 0; c < cols; c++)
      for (let r = 0; r < rows; r++) out[c * rows + r] = v[r][c];
    return out;
  }
  const flat = v instanceof Float64Array ? v.slice() : Float64Array.from(v);
  if (flat.length !== rows * cols)
    throw new Error(
      `${name}: expected ${rows * cols} values, got ${flat.length}`);
  return flat;
}

/** Mirrors the numpy `NumpyRegulator`: a stateless control law mapping a
 *  state estimate to commands, holding the operating point it flies about —
 *  the reference plus every MATRIX-role coefficient the law takes as data
 *  (an LQR's gain `K` and feed-forward `u_ff`), each defaulting to the built
 *  solve. `retarget()` moves the reference alone and does NOT re-solve the
 *  gain (exact only where the dynamics are invariant along the move — a
 *  translation, not a heading change); `reprogram()` installs a whole
 *  re-solved operating point, e.g. one fetched from a retarget service. */
export class Regulator {
  constructor(runtime) {
    this.rt = runtime;
    this._ctrl = byMethod["control"];
    if (!this._ctrl)
      throw new Error("Module exposes no `control` entry point");
    // Held reference point(s): every STATE-role port that isn't the live `x`.
    this._refs = {};
    for (const r of descriptor.stateRefs)
      if (r.name !== "x") this._refs[r.name] = Float64Array.from(r.init);
    this._refName = Object.keys(this._refs)[0]; // conventionally "x_ref"
    this._xInit = (descriptor.stateRefs.find((r) => r.name === "x")
      || { init: [] }).init;
    // Law coefficients supplied as data; defaults are the built solve.
    this._coeffs = {};
    this._shapes = {};
    for (const m of descriptor.matrixPorts || [])
      if (m.init) {
        this._coeffs[m.name] = Float64Array.from(m.init);
        this._shapes[m.name] = m.shape;
      }
  }

  /** The live reference point (flat Float64Array), or null if not retargetable. */
  get xRef() {
    return this._refName ? this._refs[this._refName].slice() : null;
  }

  /** The live feedback gain, flat column-major, or null if the law has none. */
  get gain() {
    return this._coeffs.K ? this._coeffs.K.slice() : null;
  }

  /** The live feed-forward command, or null if the law has none. */
  get uFf() {
    return this._coeffs.u_ff ? this._coeffs.u_ff.slice() : null;
  }

  /** Move the reference the law regulates to (flat or `{slot: value}`, merged
   *  over the current reference). The gain K is NOT re-solved. */
  retarget(state) {
    if (!this._refName)
      throw new Error("control law has no reference port — not retargetable");
    this._refs[this._refName] = packState(state, this._refs[this._refName]);
  }

  /** Install a re-solved operating point: gain, feed-forward and reference
   *  together (a gain is only valid about the point it was solved at). Takes
   *  a manta `LQRSolution` straight off the wire — `{K, u_ff, x_ref}`, with
   *  `K` either an array of rows (what `K.tolist()` serializes to) or a flat
   *  column-major array. camelCase keys (`uFf`, `xRef`) are accepted too. */
  reprogram(solution) {
    const K = solution.K;
    const uFf = solution.u_ff !== undefined ? solution.u_ff : solution.uFf;
    const xRef = solution.x_ref !== undefined ? solution.x_ref : solution.xRef;
    if (K === undefined || uFf === undefined || xRef === undefined)
      throw new Error(
        "reprogram: solution needs K, u_ff and x_ref (a manta LQRSolution)");
    for (const [name, v] of [["K", K], ["u_ff", uFf]]) {
      if (!this._shapes[name])
        throw new Error(`control law has no ${name} port — not reprogrammable`);
      this._coeffs[name] = packMatrix(v, this._shapes[name], name);
    }
    this.retarget(xRef instanceof Float64Array ? xRef : Float64Array.from(xRef));
  }

  /** Map a state estimate (flat or `{slot: value}`, merged over the live
   *  reference) to `{input: value}`. */
  control(state) {
    const base = this._refName ? this._refs[this._refName] : this._xInit;
    const x = packState(state, base);
    const args = {};
    for (const s of this._ctrl.in) {
      if (s.name === "x") args.x = x;
      else if (s.kind === "state") args[s.name] = this._refs[s.name];
      else if (s.kind === "matrix") {
        if (!this._coeffs[s.name])
          throw new Error(
            `control: matrix port ${JSON.stringify(s.name)} has no built ` +
            `default — reprogram() it before calling (a zero matrix is ` +
            `not a control law)`);
        args[s.name] = this._coeffs[s.name];
      }
      else if (s.kind === "parameter")
        args[s.name] = packParams({}, DEFAULT_PARAMS);
    }
    return unpackControl(this.rt.call("control", args).u);
  }
}

/** Instantiate the WASM module and return a ready `Runtime`. */
export async function load(opts = {}) {
  const Module = await createModule(opts);
  return new Runtime(Module);
}
"""
