"""Shared formatting helpers used by the emit/* modules."""

from __future__ import annotations

GENERATED_BANNER = (
    "// AUTOGENERATED by manta-codegen. You MAY edit this file as a starting\n"
    "// point for your own customizations — re-running codegen will overwrite.\n"
)

CPP_INCLUDE_GUARD = "#pragma once\n"


def cpp_float(x: float | int) -> str:
    """Format a Python number as a C++ float literal with the `f` suffix.

    Always emits a decimal point so integer-valued zeros become "0.0f" rather
    than "0f" (which is not valid C++ syntax)."""
    s = f"{float(x):.7g}"
    if "." not in s and "e" not in s and "E" not in s:
        s += ".0"
    return s + "f"


def cpp_identifier(s: str) -> str:
    """Return s if it's a valid C++ identifier, else raise."""
    if not s.isidentifier():
        raise ValueError(f"{s!r} is not a valid C++ identifier")
    return s


def class_name_for_craft(craft_name: str) -> str:
    """Convert snake_case craft name to PascalCase C++ class name + 'Craft' suffix.

    >>> class_name_for_craft("my_drone")
    'MyDroneCraft'
    """
    return "".join(p.capitalize() for p in craft_name.split("_")) + "Craft"
