"""Emit <name>.cmake — CMake fragment for the user to include.

The fragment exposes:

* `manta_<craft>_SOURCES`         — list of generated .cpp files
* `manta_<craft>_HEADERS`         — list of generated .hpp files
* `manta_<craft>_CONFIG_INCLUDE`  — the `-include path/to/<craft>_config.h` flag

For workflow="binary", also defines a target `<craft>` that links manta and
the generated main + craft sources. The user only needs:

    include(${CMAKE_CURRENT_SOURCE_DIR}/generated/<craft>/<craft>.cmake)

For workflow="library", the user composes the source list into their own
target.
"""

from __future__ import annotations

from ..core import Craft


def emit_cmake_fragment(craft: Craft, workflow: str) -> str:
    name = craft.name
    lines: list[str] = [
        f"# AUTOGENERATED by manta-codegen for craft '{name}'.",
        "",
        f"set(manta_{name}_DIR ${{CMAKE_CURRENT_LIST_DIR}})",
        "",
        f"set(manta_{name}_SOURCES",
        f"    ${{manta_{name}_DIR}}/{name}.cpp",
    ]
    if workflow in ("binary", "real_data"):
        lines.append(f"    ${{manta_{name}_DIR}}/{name}_main.cpp")
    lines += [
        ")",
        "",
        f"set(manta_{name}_HEADERS",
        f"    ${{manta_{name}_DIR}}/{name}.hpp",
        f"    ${{manta_{name}_DIR}}/{name}_config.h",
        ")",
        "",
        f'set(manta_{name}_CONFIG_INCLUDE "-include${{manta_{name}_DIR}}/{name}_config.h")',
        "",
        "# Helper: apply this craft's config-header force-include + include path",
        "# to a target. The user calls this on whichever target builds the",
        "# generated source. Required because the feature-test macros must be",
        "# uniform across every TU of the binary that contains parts using them.",
        f"function(manta_{name}_apply target)",
        f"    target_include_directories(${{target}} PRIVATE ${{manta_{name}_DIR}})",
        f"    target_compile_options(${{target}} PRIVATE \"SHELL:-include ${{manta_{name}_DIR}}/{name}_config.h\")",
        "endfunction()",
        "",
    ]

    if workflow in ("binary", "real_data"):
        # Binary + real_data workflows use Zenoh. Set it up if the
        # enclosing project hasn't already (idempotent: skips when the target
        # already exists, e.g. when building inside the manta repo's examples).
        lines += [
            "if(NOT TARGET zenohcxx::zenohc)",
            "    include(FetchContent)",
            '    set(_manta_zenoh_version "1.9.0")',
            "    if(CMAKE_SYSTEM_PROCESSOR MATCHES \"x86_64|amd64|AMD64\")",
            '        set(_manta_zenohc_arch "x86_64-unknown-linux-gnu")',
            "    elseif(CMAKE_SYSTEM_PROCESSOR MATCHES \"aarch64|arm64\")",
            '        set(_manta_zenohc_arch "aarch64-unknown-linux-gnu")',
            "    else()",
            '        message(FATAL_ERROR "manta-codegen: no pre-built zenoh-c for ${CMAKE_SYSTEM_PROCESSOR}")',
            "    endif()",
            "    FetchContent_Declare(zenohc_binary",
            '        URL "https://github.com/eclipse-zenoh/zenoh-c/releases/download/${_manta_zenoh_version}/zenoh-c-${_manta_zenoh_version}-${_manta_zenohc_arch}-standalone.zip")',
            "    FetchContent_GetProperties(zenohc_binary)",
            "    if(NOT zenohc_binary_POPULATED)",
            "        FetchContent_Populate(zenohc_binary)",
            "    endif()",
            "    find_package(zenohc REQUIRED CONFIG",
            '        PATHS "${zenohc_binary_SOURCE_DIR}/lib/cmake/zenohc" NO_DEFAULT_PATH)',
            '    set(ZENOHCXX_ENABLE_TESTS    OFF CACHE BOOL "" FORCE)',
            '    set(ZENOHCXX_ENABLE_EXAMPLES OFF CACHE BOOL "" FORCE)',
            '    set(ZENOHCXX_ZENOHPICO       OFF CACHE BOOL "" FORCE)',
            "    FetchContent_Declare(zenohcxx",
            "        GIT_REPOSITORY https://github.com/eclipse-zenoh/zenoh-cpp.git",
            "        GIT_TAG        ${_manta_zenoh_version} GIT_SHALLOW TRUE)",
            "    FetchContent_MakeAvailable(zenohcxx)",
            "endif()",
            "",
            f"add_executable({name} ${{manta_{name}_SOURCES}})",
            f"target_link_libraries({name} PRIVATE manta::manta zenohcxx::zenohc)",
            f"manta_{name}_apply({name})",
            "",
        ]

    return "\n".join(lines)
