"""A compact, geometry-preserving basis for distributed panel drag.

The part evaluates

    wrench = rho * (D1 @ nu + B @ signed_square(A @ nu))

where ``nu = [v_com, omega]`` is expressed in the part frame.  ``A`` projects
the rigid-body velocity into selected local panel-velocity components and
``B`` lifts the resulting scalar quadratic forces back into a six-axis wrench
about the part origin.  Rows with the same projection can be merged by adding
their columns in ``B``.

Unlike :class:`FossenDamping`, the nonlinear basis is not restricted to the
six element-wise terms ``nu_i * abs(nu_i)``.  It therefore retains the mixed
translation/rate terms generated by offset drag panels without retaining one
runtime Part per panel.  The matrices are fixed model constants: geometry is
compiled once and there is no runtime traversal of the source panels.
"""

from __future__ import annotations

from typing import ClassVar

import casadi as ca
import numpy as np

from ...fields import FluidField
from ...ir.frames import PartFrame, WorldFrame
from ...ir.types import Vec3
from ...ir.wrench import Wrench
from .._declarations import Parameter, PartUpdate
from ..base import Part


class ProjectedVelocityDamping(Part):
    """One constant projected-velocity drag kernel about the craft COM.

    Parameters are per unit fluid density and use Manta's additive wrench
    sign convention. ``linear_tensor`` is 6x6, ``velocity_projection`` is
    Nx6, and ``wrench_projection`` is 6xN.
    """

    requires_fields: ClassVar[list[type]] = [FluidField]

    linear_tensor: tuple = Parameter((np.zeros((6, 6)),))
    velocity_projection: tuple = Parameter((np.zeros((1, 6)),))
    wrench_projection: tuple = Parameter((np.zeros((6, 1)),))

    def __init__(
        self,
        name: str,
        *,
        linear_tensor,
        velocity_projection,
        wrench_projection,
        **overrides,
    ) -> None:
        linear = np.asarray(linear_tensor, dtype=float)
        basis = np.asarray(velocity_projection, dtype=float)
        lift = np.asarray(wrench_projection, dtype=float)
        if linear.shape != (6, 6):
            raise ValueError(
                f"ProjectedVelocityDamping {name!r}: linear_tensor must be "
                f"shape (6, 6), got {linear.shape}"
            )
        if basis.ndim != 2 or basis.shape[1] != 6 or basis.shape[0] < 1:
            raise ValueError(
                f"ProjectedVelocityDamping {name!r}: velocity_projection "
                f"must be shape (N, 6) with N >= 1, got {basis.shape}"
            )
        if lift.shape != (6, basis.shape[0]):
            raise ValueError(
                f"ProjectedVelocityDamping {name!r}: wrench_projection must "
                f"be shape (6, {basis.shape[0]}), got {lift.shape}"
            )
        if not all(np.isfinite(matrix).all() for matrix in (linear, basis, lift)):
            raise ValueError(
                f"ProjectedVelocityDamping {name!r}: matrices must be finite"
            )
        overrides.update(
            linear_tensor=(linear,),
            velocity_projection=(basis,),
            wrench_projection=(lift,),
        )
        super().__init__(name, **overrides)

    def update(self, ctx) -> PartUpdate:
        fluid = ctx.field(FluidField).value_at_sym(
            ctx.position[WorldFrame], ctx.t
        )
        part_from_world = ctx.orientation.conjugate()
        velocity = part_from_world.apply(
            ctx.velocity[WorldFrame] - fluid.velocity
        )._mx
        omega = part_from_world.apply(
            ctx.angular_velocity[WorldFrame]
        )._mx
        nu = ca.vertcat(velocity, omega)
        linear = ca.MX(self.linear_tensor[0])
        basis = ca.MX(self.velocity_projection[0])
        lift = ca.MX(self.wrench_projection[0])
        projected = basis @ nu
        wrench6 = fluid.density * (
            linear @ nu + lift @ (projected * ca.fabs(projected))
        )
        return PartUpdate(
            wrench=Wrench(
                force=Vec3[PartFrame].from_mx(wrench6[:3]),
                torque=Vec3[PartFrame].from_mx(wrench6[3:]),
            )
        )


__all__ = ["ProjectedVelocityDamping"]
