"""Eigen-shaped C++ wrapper around an EKF's flat-C kernels.

Emits a **stateful** filter class (unlike the Sim wrapper, which is a pure
evaluator): it holds the nominal state `x` and the tangent covariance `P`,
and exposes `predict` + per-sensor `update_*`. The dense linear algebra
(`F P Fᵀ + L Σ Lᵀ`, the Joseph update) is Eigen; all manifold math is
delegated to the kernels (the `boxplus` kernel applies the Kalman
correction), so no SO(3) code is written here.

The numerics mirror `manta.codegen.numpy.NumpyEKF` exactly:
  predict:  x ← f(x,u,dt,t);  P ← F P Fᵀ + L Σ Lᵀ
  update:   y = z − h(x,u);  S = H P Hᵀ + R;  K = P Hᵀ S⁻¹;
            x ← x ⊞ K y;  P ← (I−KH) P (I−KH)ᵀ + K R Kᵀ   (R = L_h Σ L_hᵀ)
"""

from __future__ import annotations

from pathlib import Path

from . import _structs as S
from .extract_ekf import EkfFunctions


def _call(fn: str, args: list[str], results: list[tuple[int, str]]) -> list[str]:
    """Emit a CasADi flat-C kernel call (arg/res/iw/w boilerplate)."""
    out = [f"    {{",
           f"        const double* arg[{fn}_SZ_ARG] = {{0}};"]
    out += [f"        arg[{i}] = {a};" for i, a in enumerate(args)]
    out.append(f"        double* res[{fn}_SZ_RES] = {{0}};")
    out += [f"        res[{i}] = {e};" for i, e in results]
    out.append(f"        long long iw[{fn}_SZ_IW > 0 ? {fn}_SZ_IW : 1];")
    out.append(f"        double    w [{fn}_SZ_W  > 0 ? {fn}_SZ_W  : 1];")
    out.append(f"        {fn}(arg, res, iw, w, 0);")
    out.append("    }")
    return out


def _matrix_literal(M, rows: int, cols: int) -> str:
    """Eigen comma-initializer body for a baked constant matrix (row-major)."""
    vals = ", ".join(repr(float(M[i, j])) for i in range(rows) for j in range(cols))
    return vals


def _contiguous_ranges(blocks, n: int):
    """If `blocks` partition [0, n) into contiguous index ranges, return them
    as `[(start, length), …]` (sorted); else `None`. The
    independent-subsystem partition is contiguous in practice (per-owner
    tangent layout); the wrapper falls back to a dense propagation otherwise.
    """
    ranges = []
    for b in blocks:
        s = sorted(int(i) for i in b)
        if s != list(range(s[0], s[-1] + 1)):
            return None
        ranges.append((s[0], len(s)))
    ranges.sort()
    covered, expect = [], 0
    for start, length in ranges:
        if start != expect:
            return None
        expect += length
    return ranges if expect == n else None


def _predict_cov_lines(blocks, n: int, has_L: bool) -> list[str]:
    """Emit the covariance propagation `P ← F P Fᵀ + L Σ Lᵀ`.

    Per independent block when the partition is contiguous (`Σ O(n_b³)` for
    uncoupled multi-craft, matching the numpy EKF); a single dense step
    otherwise. Off-block covariance is zero by construction of the partition
    and stays untouched."""
    ranges = _contiguous_ranges(blocks, n)
    if ranges is None or len(ranges) == 1:
        if has_L:
            return ["    P = F * P * F.transpose() + Ln * SIGMA * Ln.transpose();"]
        return ["    P = F * P * F.transpose();"]
    out = ["    // Per-block propagation (independent subsystems)."]
    for start, ln in ranges:
        out.append("    {")
        out.append(f"        auto Fb = F.block<{ln}, {ln}>({start}, {start});")
        out.append(f"        Eigen::Matrix<double, {ln}, {ln}> Pb = "
                   f"Fb * P.block<{ln}, {ln}>({start}, {start}) * Fb.transpose();")
        if has_L:
            out.append(f"        auto Lb = Ln.block<{ln}, n_noise>({start}, 0);")
            out.append("        Pb += Lb * SIGMA * Lb.transpose();")
        out.append(f"        P.block<{ln}, {ln}>({start}, {start}) = Pb;")
        out.append("    }")
    return out


def emit_ekf_wrapper(funcs: EkfFunctions, world, out_dir: str | Path, *,
                     class_name: str, basename: str | None = None,
                     namespace: str = "manta_gen") -> dict[str, Path]:
    out_dir = Path(out_dir).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    base = basename or class_name.lower()
    hpp = out_dir / f"{base}.hpp"
    cpp = out_dir / f"{base}.cpp"
    hpp.write_text(_build_hpp(funcs, world, class_name=class_name,
                              namespace=namespace))
    cpp.write_text(_build_cpp(funcs, world, class_name=class_name,
                              namespace=namespace, hpp_header=hpp.name,
                              kernels_header=f"{base}_kernels.h"))
    return {"hpp": hpp, "cpp": cpp}


def _build_hpp(funcs: EkfFunctions, world, *, class_name: str,
               namespace: str) -> str:
    spec = funcs.spec
    n = spec.tangent_dim
    L = ["// Generated by manta.codegen. Do not edit by hand.", "",
         "#pragma once", "", "#include <Eigen/Dense>", "",
         f"namespace {namespace} {{", "", f"class {class_name} {{",
         "public:",
         f"    static constexpr int ambient_dim = {spec.ambient_dim};",
         f"    static constexpr int tangent_dim = {n};",
         f"    static constexpr int n_inputs    = {funcs.n_inputs};",
         f"    static constexpr int n_noise     = {funcs.Sigma.shape[0]};",
         "    using Cov = Eigen::Matrix<double, tangent_dim, tangent_dim>;",
         ""]
    L += S.state_struct_lines(spec, world) + [""]
    L += S.inputs_struct_lines(funcs.input_names, world) + [""]
    L += ["    State x;          // nominal state (ambient)",
          "    Cov   P;          // error-state covariance (tangent)",
          "",
          f"    {class_name}();",
          "    void reset(const State& x0, const Cov& P0);",
          "    const State& state() const { return x; }",
          "    const Cov&   covariance() const { return P; }",
          "",
          "    void predict(const Inputs& u, double dt, double t = 0.0);",
          ""]
    for s in funcs.sensors:
        zt = S.eigen_vec_type(s.out_dim)
        L.append(f"    void update_{S.cpp_ident(s.full_name)}("
                 f"const {zt}& z, const Inputs& u, double t = 0.0);")
    L += ["};", "", f"}}  // namespace {namespace}"]
    return "\n".join(L) + "\n"


def _build_cpp(funcs: EkfFunctions, world, *, class_name: str, namespace: str,
               hpp_header: str, kernels_header: str) -> str:
    spec = funcs.spec
    q = class_name
    n = spec.tangent_dim
    nz = funcs.Sigma.shape[0]
    L = ["// Generated by manta.codegen. Do not edit by hand.", "",
         f'#include "{hpp_header}"', "", "#include <Eigen/Dense>", "",
         'extern "C" {', f'#include "{kernels_header}"', "}", "",
         f"namespace {namespace} {{", ""]

    # pack/unpack (shared helpers).
    L += S.pack_state_lines(spec, q) + [""]
    L += S.unpack_state_lines(spec, q) + [""]
    L += S.pack_inputs_lines(funcs.input_names, q) + [""]

    # Baked constants: process covariance Σ and the default P0.
    if nz > 0:
        L.append(f"static const Eigen::Matrix<double, {nz}, {nz}> SIGMA = "
                 f"(Eigen::Matrix<double, {nz}, {nz}>() << "
                 f"{_matrix_literal(funcs.Sigma, nz, nz)}).finished();")
    L.append(f"static const {q}::Cov P0_DEFAULT = ({q}::Cov() << "
             f"{_matrix_literal(funcs.P0, n, n)}).finished();")
    L.append("")

    u_decl = (f"    double u_in[{funcs.n_inputs}];" if funcs.n_inputs > 0
              else "    double u_in[1] = {0.0};")

    # Constructor / reset.
    L += [f"{q}::{q}() {{ x = State{{}}; P = P0_DEFAULT; }}",
          "",
          f"void {q}::reset(const State& x0, const Cov& P0) {{ x = x0; P = P0; }}",
          ""]

    # ---- predict ----
    pf, Ff = funcs.predict_fn.name(), funcs.F_fn.name()
    L += [f"void {q}::predict(const Inputs& u, double dt, double t) {{",
          f"    double x_in[{spec.ambient_dim}], x_out[{spec.ambient_dim}];",
          u_decl,
          "    pack_state(x, x_in);",
          "    pack_inputs(u, u_in);",
          "    Eigen::Matrix<double, tangent_dim, tangent_dim, Eigen::ColMajor> F;"]
    has_L = funcs.L_fn is not None and nz > 0
    L += _call(pf, ["x_in", "u_in", "&dt", "&t"], [(0, "x_out")])
    L += _call(Ff, ["x_in", "u_in", "&dt", "&t"], [(0, "F.data()")])
    if has_L:
        L += ["    Eigen::Matrix<double, tangent_dim, n_noise, Eigen::ColMajor> Ln;"]
        L += _call(funcs.L_fn.name(), ["x_in", "u_in", "&dt", "&t"],
                   [(0, "Ln.data()")])
    L += _predict_cov_lines(funcs.blocks, n, has_L)
    L += ["    unpack_state(x_out, x);",   # x_new (uses pre-predict F/L above)
          "    P = 0.5 * (P + P.transpose()).eval();",
          "}", ""]

    # ---- per-sensor update ----
    for s in funcs.sensors:
        d = s.out_dim
        ident = S.cpp_ident(s.full_name)
        zt = S.eigen_vec_type(d)
        hf, Hf = s.h_fn.name(), s.H_fn.name()
        L += [f"void {q}::update_{ident}(const {zt}& z, const Inputs& u, double t) {{",
              f"    double x_in[{spec.ambient_dim}], x_out[{spec.ambient_dim}];",
              u_decl,
              "    double dt = 0.0;",
              "    pack_state(x, x_in);",
              "    pack_inputs(u, u_in);",
              f"    Eigen::Matrix<double, {d}, 1> hvec;",
              f"    Eigen::Matrix<double, {d}, tangent_dim, Eigen::ColMajor> H;"]
        L += _call(hf, ["x_in", "u_in", "&dt", "&t"], [(0, "hvec.data()")])
        L += _call(Hf, ["x_in", "u_in", "&dt", "&t"], [(0, "H.data()")])
        L += [f"    Eigen::Matrix<double, {d}, {d}> R = "
              f"Eigen::Matrix<double, {d}, {d}>::Zero();"]
        if s.L_h_fn is not None and nz > 0:
            Lhf = s.L_h_fn.name()
            L += [f"    Eigen::Matrix<double, {d}, n_noise, Eigen::ColMajor> Lh;"]
            L += _call(Lhf, ["x_in", "u_in", "&dt", "&t"], [(0, "Lh.data()")])
            L += ["    R = Lh * SIGMA * Lh.transpose();"]
        # z as a fixed column vector (double for d==1).
        zexpr = ("(Eigen::Matrix<double, 1, 1>() << z).finished()" if d == 1
                 else "z")
        L += [f"    Eigen::Matrix<double, {d}, 1> y = {zexpr} - hvec;",
              f"    Eigen::Matrix<double, {d}, {d}> Sm = H * P * H.transpose() + R;",
              "    Eigen::Matrix<double, tangent_dim, " + str(d) + "> K = "
              "P * H.transpose() * Sm.inverse();",
              "    Eigen::Matrix<double, tangent_dim, 1> delta = K * y;",
              "    pack_state(x, x_in);"]
        L += _call(funcs.boxplus_fn.name(), ["x_in", "delta.data()"], [(0, "x_out")])
        L += ["    unpack_state(x_out, x);",
              "    Cov IKH = Cov::Identity() - K * H;",
              "    P = IKH * P * IKH.transpose() + K * R * K.transpose();",
              "    P = 0.5 * (P + P.transpose()).eval();",
              "}", ""]

    L += [f"}}  // namespace {namespace}"]
    return "\n".join(L) + "\n"
