"""Eigen-typed C++ wrapper around an EKF's baked Kalman kernels.

Emits a **stateful** filter class holding the nominal state `x` and the
tangent covariance `P`, exposing `predict` + per-sensor `update_*`. Each
method is pure pack/call/unpack: the *entire* Kalman recursion — `F P Fᵀ +
Q`, the Joseph update, the manifold `boxplus` correction — lives inside the
generated kernels (`Linearization.kalman_functions`), so **no linear algebra
is written here**. This mirrors `NumpyEKF`, which evaluates the very same
kernels; the only per-backend code is struct typing + the flat-array glue.
"""

from __future__ import annotations

from pathlib import Path

from . import _structs as S
from ._casadi import emit_kernel_call as _call
from .extract_ekf import EkfFunctions


def _matrix_literal(M, rows: int, cols: int) -> str:
    """Eigen comma-initializer body for a baked constant matrix (row-major)."""
    return ", ".join(repr(float(M[i, j]))
                     for i in range(rows) for j in range(cols))


def emit_ekf_wrapper(funcs: EkfFunctions, world, out_dir: str | Path, *,
                     class_name: str, basename: str | None = None,
                     namespace: str = "manta_gen") -> dict[str, Path]:
    out_dir = Path(out_dir).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    base = basename or class_name.lower()
    hpp = out_dir / f"{base}.hpp"
    cpp = out_dir / f"{base}.cpp"
    hpp.write_text(_build_hpp(funcs, world, class_name=class_name,
                              namespace=namespace))
    cpp.write_text(_build_cpp(funcs, world, class_name=class_name,
                              namespace=namespace, hpp_header=hpp.name,
                              kernels_header=f"{base}_kernels.h"))
    return {"hpp": hpp, "cpp": cpp}


def _build_hpp(funcs: EkfFunctions, world, *, class_name: str,
               namespace: str) -> str:
    spec = funcs.spec
    L = ["// Generated by manta.codegen. Do not edit by hand.", "",
         "#pragma once", "", "#include <Eigen/Dense>", "",
         f"namespace {namespace} {{", "", f"class {class_name} {{",
         "public:",
         f"    static constexpr int ambient_dim = {spec.ambient_dim};",
         f"    static constexpr int tangent_dim = {spec.tangent_dim};",
         f"    static constexpr int n_inputs    = {funcs.n_inputs};",
         "    using Cov = Eigen::Matrix<double, tangent_dim, tangent_dim>;",
         ""]
    L += S.state_struct_lines(spec, world) + [""]
    L += S.inputs_struct_lines(funcs.input_names, world) + [""]
    L += ["    State x;          // nominal state (ambient)",
          "    Cov   P;          // error-state covariance (tangent)",
          "",
          f"    {class_name}();",
          "    void reset(const State& x0, const Cov& P0);",
          "    const State& state() const { return x; }",
          "    const Cov&   covariance() const { return P; }",
          "",
          "    void predict(const Inputs& u, double dt, double t = 0.0);",
          ""]
    for s in funcs.sensors:
        zt = S.eigen_vec_type(s.out_dim)
        L.append(f"    void update_{S.cpp_ident(s.full_name)}("
                 f"const {zt}& z, const Inputs& u, double t = 0.0);")
    L += ["};", "", f"}}  // namespace {namespace}"]
    return "\n".join(L) + "\n"


def _build_cpp(funcs: EkfFunctions, world, *, class_name: str, namespace: str,
               hpp_header: str, kernels_header: str) -> str:
    spec = funcs.spec
    q = class_name
    n = spec.tangent_dim
    amb = spec.ambient_dim
    L = ["// Generated by manta.codegen. Do not edit by hand.", "",
         f'#include "{hpp_header}"', "", "#include <Eigen/Dense>", "",
         'extern "C" {', f'#include "{kernels_header}"', "}", "",
         f"namespace {namespace} {{", ""]

    L += S.pack_state_lines(spec, q) + [""]
    L += S.unpack_state_lines(spec, q) + [""]
    L += S.pack_inputs_lines(funcs.input_names, q) + [""]

    # Default initial covariance (the only baked constant — Σ and the
    # Jacobians now live inside the kernels).
    L += [f"static const {q}::Cov P0_DEFAULT = ({q}::Cov() << "
          f"{_matrix_literal(funcs.P0, n, n)}).finished();", ""]

    u_decl = (f"    double u_in[{funcs.n_inputs}];" if funcs.n_inputs > 0
              else "    double u_in[1] = {0.0};")

    L += [f"{q}::{q}() {{ x = State{{}}; P = P0_DEFAULT; }}", "",
          f"void {q}::reset(const State& x0, const Cov& P0) {{ x = x0; P = P0; }}",
          ""]

    # ---- predict: pack → (Q kernel) → predict kernel → unpack ----
    L += [f"void {q}::predict(const Inputs& u, double dt, double t) {{",
          f"    double x_in[{amb}], x_out[{amb}];", u_decl,
          "    pack_state(x, x_in);",
          "    pack_inputs(u, u_in);",
          "    Cov Qm = Cov::Zero();"]
    if funcs.process_noise_fn is not None:
        L += _call(funcs.process_noise_fn.name(),
                   ["x_in", "u_in", "&dt", "&t"], [(0, "Qm.data()")])
    L += ["    Cov Pout;"]
    L += _call(funcs.predict_fn.name(),
               ["x_in", "P.data()", "Qm.data()", "u_in", "&dt", "&t"],
               [(0, "x_out"), (1, "Pout.data()")])
    L += ["    unpack_state(x_out, x);", "    P = Pout;", "}", ""]

    # ---- per-sensor update: pack → update kernel → unpack ----
    for s in funcs.sensors:
        ident = S.cpp_ident(s.full_name)
        zt = S.eigen_vec_type(s.out_dim)
        zp = "&z" if s.out_dim == 1 else "z.data()"
        L += [f"void {q}::update_{ident}(const {zt}& z, const Inputs& u, "
              f"double t) {{",
              f"    double x_in[{amb}], x_out[{amb}];", u_decl,
              "    pack_state(x, x_in);",
              "    pack_inputs(u, u_in);",
              "    Cov Pout;"]
        L += _call(s.update_fn.name(),
                   ["x_in", "P.data()", zp, "u_in", "&t"],
                   [(0, "x_out"), (1, "Pout.data()")])
        L += ["    unpack_state(x_out, x);", "    P = Pout;", "}", ""]

    L += [f"}}  // namespace {namespace}"]
    return "\n".join(L) + "\n"
