"""Eigen-shaped C++ wrapper around an LQR's baked control law.

The LQR IR's `control_fn` already bakes the gain, the operating point, and
the manifold `boxminus` into one function `x_full → u` (`u = u_ref − K·(x ⊟
x_ref)`). So the C++ side is a thin **stateless** evaluator: pack the state
estimate, call the one kernel, unpack the commands — mirroring the Sim
wrapper's `measure_*` pattern.
"""

from __future__ import annotations

from pathlib import Path

from . import _structs as S


def emit_lqr_wrapper(spec, input_names, control_kernel: str, world,
                     out_dir: str | Path, *, class_name: str,
                     basename: str | None = None,
                     namespace: str = "manta_gen") -> dict[str, Path]:
    out_dir = Path(out_dir).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    base = basename or class_name.lower()
    hpp = out_dir / f"{base}.hpp"
    cpp = out_dir / f"{base}.cpp"
    n_u = len(input_names)

    H = ["// Generated by manta.codegen. Do not edit by hand.", "",
         "#pragma once", "", "#include <Eigen/Dense>", "",
         f"namespace {namespace} {{", "", f"class {class_name} {{",
         "public:",
         f"    static constexpr int ambient_dim = {spec.ambient_dim};",
         f"    static constexpr int n_inputs    = {n_u};", ""]
    H += S.state_struct_lines(spec, world) + [""]
    H += S.inputs_struct_lines(input_names, world) + [""]
    H += ["    // Map a state estimate to the LQR command u = u_ref - K(x ⊟ x_ref).",
          "    Inputs control(const State& x) const;",
          "};", "", f"}}  // namespace {namespace}"]
    hpp.write_text("\n".join(H) + "\n")

    C = ["// Generated by manta.codegen. Do not edit by hand.", "",
         f'#include "{hpp.name}"', "",
         'extern "C" {', f'#include "{base}_kernels.h"', "}", "",
         f"namespace {namespace} {{", ""]
    C += S.pack_state_lines(spec, class_name) + [""]
    C += [f"{class_name}::Inputs {class_name}::control(const State& x) const {{",
          f"    double x_in[{spec.ambient_dim}];",
          f"    double u_out[{max(n_u, 1)}];",
          "    pack_state(x, x_in);",
          f"    const double* arg[{control_kernel}_SZ_ARG] = {{0}};",
          "    arg[0] = x_in;",
          f"    double* res[{control_kernel}_SZ_RES] = {{0}};",
          "    res[0] = u_out;",
          f"    long long iw[{control_kernel}_SZ_IW > 0 ? {control_kernel}_SZ_IW : 1];",
          f"    double    w [{control_kernel}_SZ_W  > 0 ? {control_kernel}_SZ_W  : 1];",
          f"    {control_kernel}(arg, res, iw, w, 0);",
          "    Inputs u;"]
    for i, name in enumerate(input_names):
        C.append(f"    u.{S.cpp_ident(name)} = u_out[{i}];")
    C += ["    return u;", "}", "", f"}}  // namespace {namespace}"]
    cpp.write_text("\n".join(C) + "\n")
    return {"hpp": hpp, "cpp": cpp}
