"""Eigen-shaped C++ wrapper for a `recurrence` block (PID, Madgwick, IMU).

The single generic recurrence runtime on the C++ side: a stateful class
holding the ambient `State`, with one `step(const Inputs&, dt, t) ->
Outputs` that calls the block's one baked kernel (`update_fn` — two
results: next-state + readouts) and unpacks the result. No covariance and
no manifold math live here — the kernel returns the next ambient state
directly, exactly as the numpy `NumpyRecurrence` does. **Every** recurrence
block lowers through this one emitter unchanged, which is the whole point
of the `recurrence` runtime kind: a new filter/controller of this shape
costs no C++ backend code.
"""

from __future__ import annotations

from pathlib import Path

from . import _structs as S
from .ekf_wrapper import _call
from .types import cpp_type_for


def _state_init_expr(slot, x0) -> str:
    """C++ initializer for a State field, taken from the block's `x0`."""
    cpp = cpp_type_for(slot.manifold)
    seg = x0[slot.offset:slot.offset + slot.dim]
    if slot.dim == 1:
        return cpp.literal(float(seg[0]))
    return cpp.literal([float(v) for v in seg])


def emit_recurrence_wrapper(block, out_dir: str | Path, *, class_name: str,
                            basename: str | None = None,
                            namespace: str = "manta_gen") -> dict[str, Path]:
    out_dir = Path(out_dir).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    base = basename or class_name.lower()
    hpp = out_dir / f"{base}.hpp"
    cpp = out_dir / f"{base}.cpp"
    spec = block.spec
    kernel = block.update_fn.name()
    ins, outs = block.inputs, block.outputs

    # ---- header ----
    H = ["// Generated by manta.codegen. Do not edit by hand.", "",
         "#pragma once", "", "#include <Eigen/Dense>", "",
         f"namespace {namespace} {{", "", f"class {class_name} {{",
         "public:",
         f"    static constexpr int ambient_dim = {spec.ambient_dim};",
         f"    static constexpr int input_dim   = {block.input_dim};",
         f"    static constexpr int output_dim  = {block.output_dim};", ""]
    # State struct (defaults baked from x0).
    H.append("    struct State {")
    for s in spec.slots:
        H.append(f"        {S.eigen_type_for(s)} {S.cpp_ident(s.name)} "
                 f"= {_state_init_expr(s, block.x0)};")
    H.append("    };")
    # Inputs struct.
    H.append("    struct Inputs {")
    for p in ins:
        H.append(f"        {S.eigen_vec_type(p.dim)} {S.cpp_ident(p.name)} = "
                 f"{S.eigen_vec_type(p.dim)}{'(0.0)' if p.dim == 1 else '::Zero()'};")
    H.append("    };")
    # Outputs struct.
    H.append("    struct Outputs {")
    for p in outs:
        H.append(f"        {S.eigen_vec_type(p.dim)} {S.cpp_ident(p.name)};")
    H.append("    };")
    H += ["",
          "    State x;          // block state (ambient)",
          "",
          f"    {class_name}() {{ x = State{{}}; }}",
          "    void reset(const State& x0) { x = x0; }",
          "    const State& state() const { return x; }",
          "",
          "    Outputs step(const Inputs& u, double dt, double t = 0.0);",
          "};", "", f"}}  // namespace {namespace}"]
    hpp.write_text("\n".join(H) + "\n")

    # ---- source ----
    q = class_name
    C = ["// Generated by manta.codegen. Do not edit by hand.", "",
         f'#include "{hpp.name}"', "",
         'extern "C" {', f'#include "{base}_kernels.h"', "}", "",
         f"namespace {namespace} {{", ""]
    C += S.pack_state_lines(spec, q) + [""]
    C += S.unpack_state_lines(spec, q) + [""]

    # pack_inputs: concatenate the input ports into the flat u vector.
    C.append(f"static void pack_inputs(const {q}::Inputs& u, double* uflat) {{")
    off = 0
    for p in ins:
        ident = S.cpp_ident(p.name)
        if p.dim == 1:
            C.append(f"    uflat[{off}] = u.{ident};")
        else:
            for i in range(p.dim):
                C.append(f"    uflat[{off + i}] = u.{ident}[{i}];")
        off += p.dim
    C += ["}", ""]

    C += [f"{q}::Outputs {q}::step(const Inputs& u, double dt, double t) {{",
          f"    double x_in[{spec.ambient_dim}], x_out[{spec.ambient_dim}];",
          f"    double u_in[{max(block.input_dim, 1)}];",
          f"    double y_out[{max(block.output_dim, 1)}];",
          "    pack_state(x, x_in);",
          "    pack_inputs(u, u_in);"]
    C += _call(kernel, ["x_in", "u_in", "&dt", "&t"],
               [(0, "x_out"), (1, "y_out")])
    C += ["    unpack_state(x_out, x);",
          "    Outputs out;"]
    off = 0
    for p in outs:
        ident = S.cpp_ident(p.name)
        if p.dim == 1:
            C.append(f"    out.{ident} = y_out[{off}];")
        else:
            for i in range(p.dim):
                C.append(f"    out.{ident}[{i}] = y_out[{off + i}];")
        off += p.dim
    C += ["    return out;", "}", "", f"}}  // namespace {namespace}"]
    cpp.write_text("\n".join(C) + "\n")
    return {"hpp": hpp, "cpp": cpp}
