"""CMakeLists.txt fragment for a generated manta C++ library.

Emits a self-contained CMake project that:
  * compiles `<basename>_kernels.c` and `<basename>.cpp` into a static
    library named `<library_name>`;
  * uses Eigen3 via find_package, falling back to a user-provided
    EIGEN_INCLUDE_DIR cache var;
  * exports the library + interface include path so a downstream user
    can simply `add_subdirectory(generated/drone)` and link `Drone`.
"""

from __future__ import annotations

from pathlib import Path


def emit_cmakelists(out_dir: str | Path,
                    *,
                    library_name: str,
                    basename: str) -> Path:
    """Emit `CMakeLists.txt` into `out_dir`.

    Args:
        library_name — CMake target name for the generated library
                       (typically the same as the C++ class name).
        basename     — filename stem matching the kernel + wrapper output.

    Returns:
        Absolute path to the emitted CMakeLists.txt.
    """
    out_dir = Path(out_dir).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / "CMakeLists.txt"
    path.write_text(_cmake_text(library_name=library_name, basename=basename))
    return path


def _cmake_text(*, library_name: str, basename: str) -> str:
    return f"""\
# Generated by manta.codegen. Do not edit by hand.
cmake_minimum_required(VERSION 3.16)

# Standalone-friendly: if this CMakeLists is consumed via add_subdirectory
# the parent project's settings dominate. If it's used as a top-level
# project (e.g. for the roundtrip test) we declare it explicitly.
if(NOT PROJECT_NAME)
    project({library_name} CXX C)
endif()

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_C_STANDARD 11)

# --- Eigen --------------------------------------------------------------
# Prefer find_package(Eigen3); fall back to EIGEN_INCLUDE_DIR for systems
# where Eigen is installed without a CMake config.
find_package(Eigen3 QUIET NO_MODULE)
if(NOT Eigen3_FOUND)
    if(NOT EIGEN_INCLUDE_DIR)
        # Common Debian/Ubuntu path.
        if(EXISTS "/usr/include/eigen3/Eigen/Dense")
            set(EIGEN_INCLUDE_DIR "/usr/include/eigen3" CACHE PATH
                "Eigen include directory")
        endif()
    endif()
    if(NOT EIGEN_INCLUDE_DIR)
        message(FATAL_ERROR
            "Eigen3 not found. Install eigen3 or pass "
            "-DEIGEN_INCLUDE_DIR=<path-to-Eigen-headers>.")
    endif()
endif()

# --- Library target -----------------------------------------------------
add_library({library_name} STATIC
    {basename}_kernels.c
    {basename}.cpp
)

target_include_directories({library_name} PUBLIC
    ${{CMAKE_CURRENT_SOURCE_DIR}}
)

if(Eigen3_FOUND)
    target_link_libraries({library_name} PUBLIC Eigen3::Eigen)
else()
    target_include_directories({library_name} PUBLIC ${{EIGEN_INCLUDE_DIR}})
endif()

# Suppress benign warnings on the CasADi-emitted C kernel — it includes
# unused-parameter style code that's hostile to -Wall by default.
set_source_files_properties(
    {basename}_kernels.c
    PROPERTIES COMPILE_OPTIONS "-Wno-unused-parameter;-Wno-unused-variable;-Wno-missing-field-initializers"
)
"""
